### ISSUE TITLE
add pydicom to file tree

### ISSUE THREAD

**Issue by patmo141** [patmo141/volume_render#3]
Did you do anything other than copy/paste to add the pydicom directory? I have temporarily copied it from my Blender modules folder into the addon folder.  Can I commit that change if that's all that it takes but I remember the dateutil dependency which may be masked by the fact that dateutil is in my modules folder.

![image](https://cloud.githubusercontent.com/assets/2917743/15247579/383fb710-18e3-11e6-85e6-db728b1ade13.png)

**Comment by HG1-Public** [comment]
No problem. You can “push” your changes.

From: patmo141 
Sent: Friday, May 13, 2016 2:32 PM
To: patmo141/volume_render 
Subject: [patmo141/volume_render] add pydicom to file tree (#3)

Did you do anything other than copy/paste to add the pydicom directory? I have temporarily copied it from my Blender modules folder into the addon folder. Can I commit that change if that's all that it takes but I remember the dateutil dependency which may be masked by the fact that dateutil is in my modules folder.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by patmo141** [comment]
done
